app/models/creditos.py
from app.extensions import db

class Creditos(db.Model):
    """
    Representa un crédito otorgado a un cliente. 
    Hereda de la clase Model de SQLAlchemy para realizar la operaciones en la base de datos.

    Atributos:
        id (int)                 : Identificador del crédito.
        cliente (str)            : Nombre del cliente.
        monto (float)            : Monto del crédito.
        tasa_interes (float)     : Tasa de interés aplicada.
        plazo (int)              : Plazo en meses.
        fecha_otorgamiento (str) : Fecha en formato YYYY-MM-DD.
    """
    __tablename__ = 'creditos'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    cliente = db.Column(db.String(100), nullable=False)
    monto = db.Column(db.Float, nullable=False)
    tasa_interes = db.Column(db.Float, nullable=False)
    plazo = db.Column(db.Integer, nullable=False)
    fecha_otorgamiento = db.Column(db.String(100), nullable=False)

    def __init__(self, cliente, monto, tasa_interes, plazo, fecha_otorgamiento):
        self.cliente = cliente
        self.monto = monto 
        self.tasa_interes = tasa_interes
        self.plazo = plazo
        self.fecha_otorgamiento = fecha_otorgamiento

app/__init__.py
from flask import Flask
from config import Config
from .routes.creditos import creditos
from .routes.main import main
from .extensions import db
from .models.creditos import Creditos

def create_app():
    """
    Función para configurar la aplicación y registrar Blueprints

    Returns:
        Flask instance : instancia de Flask con la configuración de la app
    """
    app = Flask(__name__)
    
    app.config.from_object(Config)

    app.register_blueprint(creditos)
    app.register_blueprint(main)

    db.init_app(app)

    with app.app_context():
        db.create_all()

    return app
    

app/routes/creditos.py
# Rutas para creditos
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.creditos import Creditos
from app.extensions import db

creditos = Blueprint('creditos', __name__, url_prefix='/creditos')


@creditos.route('/add', methods=['GET', 'POST'])
def addCredit():
    """
    Agrega un nuevo crédito a la base de datos.

    Métodos:
        - GET  : Muestra el formulario de registro.
        - POST : Recibe los datos del formulario y crea un nuevo crédito en la base de datos.

    Parámetros en request.form:
        - cliente (str) : Nombre del cliente.
        - monto (float) : Monto del crédito.
        - tasa (float)  : Tasa de interés aplicada.
        - plazo (int)   : Plazo en meses.
        - fecha (str)   : Fecha de otorgamiento (YYYY-MM-DD).

    Retorna:
        - Redirige a la lista de créditos si la operación es exitosa.
        - Si la operación no es exitosa, renderiza nuevamente el formulario.
        - Renderiza el formulario con un mensaje de error si falla la operación.
    """
    if request.method == 'POST':
        try:
            cliente = request.form.get('cliente')
            monto = request.form.get('monto')
            tasa = request.form.get('tasa')
            plazo = request.form.get('plazo')
            fecha = request.form.get('fecha')

            credito = Creditos(cliente, monto, tasa, plazo, fecha)
            
            db.session.add(credito)
            db.session.commit()
            return redirect(url_for('creditos.listCredits'))
        except:
            return render_template('creditos/add.html')
    else:
        return render_template('creditos/add.html')

@creditos.route('/list')
def listCredits():
    """
    Devuelve todos los créditos ingresados en la base de datos.

    Retorna:
        - Renderiza la tabla con la lista de créditos obtenidos de la base de datos.
    """
    data = Creditos.query.all()
    return render_template('creditos/list.html', creditos = data)

@creditos.route('/delete/<int:id>')
def deleteCredit(id):
    """
    Elimina el crédito correspondiente al ID en la base de datos. 

    Parámetros:
        - id (int) : ID del crédito a eliminar.

    Flujo:
        - Busca el crédito por el ID en la base de datos.
        - Si el crédito existe, lo elimina de la base de datos.
        - Si el crédito no existe, devuelve un error 404.

    Retorna:
        - Redirige a la lista de créditos si todo es exitoso.
    """
    credito = Creditos.query.get_or_404(id)
    db.session.delete(credito)
    db.session.commit()
    return redirect(url_for('creditos.listCredits'))

@creditos.route('/edit/<int:id>', methods=['GET', 'POST'])
def editCredit(id):
    """
    Edita los datos de un crédito existente en la base de datos.

    Métodos:
        - GET  : Muestra el formulario de edición con los valores del crédito correspondiente al ID.
        - POST : Actualiza los datos del crédito en la base de datos.

    Parámetros en request.form:
        - cliente (str) : Nombre del cliente.
        - monto (float) : Monto del crédito.
        - tasa (float)  : Tasa de interés aplicada.
        - plazo (int)   : Plazo en meses.
        - fecha (str)   : Fecha de otorgamiento (YYYY-MM-DD).

    Parámetro en URL:
        - id (in) : ID del crédito a editar.

    Flujo:
        - Busca el crédito por el ID en la base de datos.
        - Si el crédito existe, modifica los atributos de la instancia y lo almacena en la base de datos.
        - Si el crédito no existe, devuelve un error 404.

    Retorna:
        - Redirige a la lista de créditos si la operación es exitosa.
        - Renderiza el formulario y devuelve un error 404.
        - Renderiza el formulario de edición con los valores del crédito correspondiente al ID.
    """
    data = Creditos.query.get_or_404(id)
    if request.method == 'POST': 
        try:   
            data.cliente = request.form.get('cliente')
            data.monto = request.form.get('monto')
            data.tasa_interes = request.form.get('tasa')
            data.plazo = request.form.get('plazo')
            data.fecha_otorgamiento = request.form.get('fecha')

            db.session.commit()
            return redirect(url_for('creditos.listCredits'))
        except:
            return render_template('creditos/edit.html', credito=data)
    else:
        return render_template('creditos/edit.html', credito=data)
    
@creditos.route('/graph')
def graphCredits():
    """
    Devuelve la información necesaria para graficar el total de créditos otorgados, el monto total,
    la distribución de monto de cada cliente y la distribución de créditos otorgados de cada cliente.

    Flujo:
        - Obtiene todos los créditos de la base de datos.
        - Almacena el total de instancias devueltas de la base de datos.
        - Suma y almacena el monto total de todos los créditos otorgados.
        - Crea dos diccionarios: uno almacena la suma del monto total por cliente y el otro almacena la cantidad de créditos otorgados por cliente.

    Retorna:
        - Renderiza las gráficas con la información de obtenida de la base de datos.
    """
    data = Creditos.query.all()
    total = len(data)
    montoTotal = sum(credito.monto for credito in data)
    distribucionClientesMonto = {}
    distribucionClientesCantidad = {}

    for credito in data:
        if credito.cliente in distribucionClientesMonto:
            distribucionClientesMonto[credito.cliente] += credito.monto
            distribucionClientesCantidad[credito.cliente] += 1
        else:
            distribucionClientesMonto[credito.cliente] = credito.monto
            distribucionClientesCantidad[credito.cliente] = 1


    return render_template('creditos/graphs.html', total=total, monto=montoTotal, distribucion=distribucionClientesMonto, cantidad=distribucionClientesCantidad)

app/routes/main.py
# Rutas para index
from flask import Blueprint, render_template

main = Blueprint('main', __name__, url_prefix='/')

@main.route('/')
def index():
    """
    Devuelve la página principal con un mensaje de bienvenida.

    Retorna:
        - Renderiza la página principal con un mensaje de bienvenida y la barra de navegación.
    """
    return render_template("index.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>Créditos</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <header>
        <h1><a href="{{ url_for('main.index')}}" class="header__titulo">Créditos Web App</a></h1>

        <ul class="navbar">
            <li class="nav-item"><a href="{{ url_for('creditos.addCredit')}}" class="navbar-item__text">Registrar</a></li>
            <li class="nav-item"><a href="{{ url_for('creditos.listCredits')}}" class="navbar-item__text">Listado</a></li>
            <li class="nav-item"><a href="{{ url_for('creditos.graphCredits')}}" class="navbar-item__text">Gráficos</a></li>
        </ul>
    </header>

    <main>
        {% block contenido %}
    
        {% endblock %}
    </main>

    <footer>

    </footer>
</body>
</html>

app/templates/creditos/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

app/templates/creditos/edit.html
{% extends "base.html" %}

{% block contenido %}

<div class="container">
    <div class="card">
        <h2>Actualiza los datos</h2>
        <form action="{{ url_for('creditos.editCredit', id=credito.id) }}" class="formulario" method="post" id="formulario">
            <label for="cliente" >Nombre del cliente:</label>
            <input type="text" name="cliente" id="cliente" value="{{ credito.cliente }}" onchange="nombreValid()">
            <span id="nombreMensaje" class="mensaje-validacion"></span>

            <label for="monto">Monto:</label>
            <input type="number" name="monto" id="monto" value="{{ credito.monto }}" onchange="montoValid()">
            <span id="montoMensaje" class="mensaje-validacion"></span>
        
            <label for="tasa">Tasa de interés (%):</label>
            <input type="number" name="tasa" id="tasa" value="{{ credito.tasa_interes }}" onchange="tasaValid()">
            <span id="tasaMensaje" class="mensaje-validacion"></span>
        
            <label for="plazo">Plazo en meses:</label>
            <input type="number" name="plazo" id="plazo" value="{{ credito.plazo }}" onchange="plazoValid()">
            <span id="plazoMensaje" class="mensaje-validacion"></span>
        
            <label for="fecha">Fecha de otorgamiento:</label>
            <input type="date" name="fecha" id="fecha" style="width: 64%;" value="{{ credito.fecha_otorgamiento }}" onchange="fechaValid()">
            <span id="fechaMensaje" class="mensaje-validacion"></span>

            <div class="button-container">
                <button type="submit" id="enviar" onsubmit="enviar()">Actualizar</button>
            </div>
        </form>
    </div>
</div>

<script src="../../static/js/validation.js"></script>

{% endblock%}

app/templates/creditos/graphs.html
{% extends "base.html" %}

{% block contenido %}

<script>
    const total = "{{ total }}"
    const monto = "{{ monto }}"
    const distribucion = JSON.parse('{{ distribucion | tojson}}')
    const cantidad = JSON.parse('{{ cantidad | tojson}}')
</script>



<div class="container-graph">
    <div class="card-graph">
        <h2>Gráfica de total créditos otorgados</h2>
        <canvas id="graph-total"></canvas>
    </div>
    
    <div class="card-graph">
        <h2>Gráfica de monto total otorgado</h2>
        <canvas id="graph-monto"></canvas>
    </div>
    
    <div class="card-graph">
        <h2>Gráfica de distribución por cliente (monto)</h2>
        <canvas id="graph-clientes"></canvas>
    </div>

    <div class="card-graph">
        <h2>Gráfica de distribución por cliente (cantidad)</h2>
        <canvas id="graph-clientes-cantidad"></canvas>
    </div>
</div>


<script src="../../static/js/graph.js"></script>

{% endblock %}

app/templates/creditos/list.html
{% extends "base.html" %}

{% block contenido %}
<div class="container">
    <table>
        <tr>
            <th>ID</th>
            <th>Cliente</th>
            <th>Monto</th>
            <th>Tasa de interés (%)</th>
            <th>Plazo (meses)</th>
            <th>Fecha de otorgamiento</th>
            <th>Acción</th>
        </tr>
        
        {% for credito in creditos %}
        <tr>
            <td>{{ credito.id }}</td>
            <td>{{ credito.cliente }}</td>
            <td>{{ credito.monto }}</td>
            <td>{{ credito.tasa_interes }}</td>
            <td>{{ credito.plazo }}</td>
            <td>{{ credito.fecha_otorgamiento }}</td>
            <td>
                <a href="{{ url_for('creditos.editCredit', id=credito.id) }}" class="button-edit"><strong>Editar</strong></a>
                <a href="{{ url_for('creditos.deleteCredit', id=credito.id) }}"
                class="button-delete"><strong>Eliminar</strong></a>
            </td>
        </tr>

        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block contenido %}

<div class="container">
    <div class="card">
        <h2 class="bienvenida">¡Bienvenido!</h2>
    </div>
</div>

{% endblock %}